<?php

/**
 * @file
 * beer_recipe.module - share beer recipes (based on recipe.module)
 */
define('BEER_RECIPE_CACHE_KEY', 'beer_recipe_markup_%s');

/**
 * Implementation of hook_form
 **/
function beer_recipe_form_beer_recipe_node_form_alter(&$form, &$form_state) 
{
	$form['title']['#required'] = FALSE;
	$form['title']['#type'] = 'hidden';
} // end function beer_recipe_form

/**
 * Implementation of hook_node_presave
 **/
function beer_recipe_entity_presave($entity, $type) 
{
	if ($type == 'node' && $entity->type == 'beer_recipe') {
		$contents = file_get_contents($entity->original->field_beer_recipe_beerxml['und'][0]['uri']);
		$dom = new DOMDocument();
		$dom->load($entity->original->field_beer_recipe_beerxml['und'][0]['uri']);
		
		$xpath = new DOMXpath($dom);
		$name = $xpath->query('//RECIPE/NAME')->item(0)->nodeValue;
		$brewer = $xpath->query('//RECIPE/BREWER')->item(0)->nodeValue;
		$entity->title = sprintf('%s by %s', $name, $brewer);

		cache_clear_all(sprintf(BEER_RECIPE_CACHE_KEY, $entity->nid), 'cache');
	}
} // end function beer_recipe_node_presave

/**
 * Implementation of hook_view
 **/
function beer_recipe_node_view($node, $view_mode, $langcode) 
{
	if ($node->type == 'beer_recipe') {
		drupal_add_css(drupal_get_path('module', 'beer_recipe') .'/beer_recipe.css');
		$cache_key = sprintf(BEER_RECIPE_CACHE_KEY, $node->nid);
		// Get the markup from cache if it's available
		if (($markup_cache = cache_get($cache_key)) === FALSE) {
			$doc = new DOMDocument();
			$doc->load($node->field_beer_recipe_beerxml['und'][0]['uri']);

			$styleDoc = new DOMDocument();
			$styleDoc->load(dirname(__FILE__) .'/beer_recipe.xsl');

			$xsl = new XSLTProcessor();
			$xsl->importStylesheet($styleDoc);

			$recipe_markup = $xsl->transformToXML($doc);
			cache_set($cache_key, $recipe_markup);
		}
		else {
			$recipe_markup = $markup_cache->data;
		}

		$node->content['beer_recipe_markup'] = array(
			'#markup' => $recipe_markup,
			'#weight' => 0,
		);
	
	}
} // end function beer_recipe_view

// vim: ft=php tabstop=2 shiftwidth=2
